config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :microposts,only: [:create,:destroy]
  root to: 'static_pages#home'
  get '/help',to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/user', to: 'users#show'
  match '/signin' ,to: 'sessions#new',via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	validates :user_id,presence:true
	belongs_to :user
	default_scope {order('microposts.created_at DESC')}
	validates :content,presence: true,length: {maximum: 140} 
end

app/models/user.rb
class User < ActiveRecord::Base
	#params.require(:user).permit(:name,:email,:password, :password_confirmation) 
	has_secure_password
	has_many :microposts,dependent: :destroy
	before_save {|user| user.email=email.downcase}
	before_save :create_remember_token
	validates :name ,presence: true,length: {maximum: 50}
	VALID_EMAIL =/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,presence: true,format: {with: VALID_EMAIL},uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {minimum: 6}
	validates :password_confirmation,presence: true
	def feed
		Micropost.where("user_id = ?", id)
	end
	private
	def create_remember_token
		self.remember_token=SecureRandom.urlsafe_base64
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_filter :signed_in_user, only: [:create,:destory]
	before_filter :courrent,only: :destroy
	def index
		
	end
	def create
		@micropost=current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success]='Micropost created!'
			redirect_to root_url
		else
			@feed_items =[]
			render 'static_pages/home'
		end
	end
	def destroy
		@micropost.destroy
		redirect_to root_url
	end
	private
  	def micropost_params
  		params.require(:micropost).permit(:content)
  	end
  	def courrent
  		@micropost=current_user.microposts.find_by_id(params[:id])
  		redirect_to root_url if @micropost.nil?
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end
	def create
		user=User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error]="Invalid email/password combination"
			render 'new'
		end
	end
	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if sign_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help

  end
  def about
  	
  end
  def contact
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,only: [:edit,:update,:index,:destroy]
  before_filter :correct_user,only: [:edit,:update]
  before_filter :admin_user,only: [:destroy]
  def new
  	@user=User.new
  end
  def show
  	@user=User.find(params[:id])
    @microposts= @user.microposts.paginate(page: params[:page])
  end
  def create
  	@user=User.new(user_params)
  	if @user.save
      sign_in @user
  		flash.now[:success]="Welcome to the Sample App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end
  def edit
    #@user=User.find(params[:id])
  end
  def update
    #@user=User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]='Profile updated'
      sign_in @user
      redirect_to @user

    else
      render 'edit'
    end
  end
  def index
    @users= User.paginate(page: params[:page])
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success]="User destroyed."
    redirect_to users_path
  end
  private
  def user_params
  	params.require(:user).permit(:name,:email,:password, :password_confirmation)
  end

  def correct_user
    @user=User.find(params[:id])
    redirect_to(root_path) unless current_user?@user
  end
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title="Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title}|#{page_title}"
		end
	end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token]=user.remember_token
		self.current_user=user
	end
	def current_user=(user)
		@current_user=user
	end
	def current_user
		@current_user||=User.find_by_remember_token(cookies[:remember_token])
	end
	def sign_in?
		!current_user.nil?
	end
	def sign_out
		self.current_user=nil
		cookies.delete(:remember_token)
	end
	def current_user?(user)
		user == current_user
	end
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end
	def store_location
		session[:return_to]=request.url  if request.get?
	end
	def signed_in_user
   		unless sign_in?
      		store_location
      		redirect_to signin_path,notice: 'Please sgin in' 
    	end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user,options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url,alt: user.name,class: 'gravatar')
		
	end
end

app/views/layouts/_footer.html.erb
<div class="row">
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Rails Tutorial</a>
		by Michael Hartl
	</small>
	<nav  class='push-right'>
	<ul class="nav nav-pills nav-right">
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><a href="http://news.railstutorial.org/">News</a></li>
	</ul>
</nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top clearfix col-md-12">
	<div class="navbar-inner">
		<div class="container">
			<nav class="navbar navbar-default" role="navigation">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to 'sample app','#',id: 'logo'%>

				</div>
			
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav">
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "Help", help_path %></li>
						<% if sign_in? %>
						<li><%= link_to 'User', users_path %></li>
						<li id='fat_menu' class='dropdown'>
							<a href="#" class='dropdown-toggle' data-toggle='dropdown'>
								Account <b class='caret'></b>
							</a>
							<ul class='dropdown-menu'>
								<li><%= link_to 'Profile',current_user%></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li><%= link_to 'Sign out',signout_path,method: 'delete'%></li>
							</ul>
						</li>
						<%else%>
						<li><%= link_to "Sign in", signin_path %></li>
						<%end%>
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Search">
						</div>
						<button type="submit" class="btn btn-default">Submit</button>
					</form>
				</div><!-- /.navbar-collapse -->
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container col-md-12">
	<% flash.each do |key,value|%>
		<div type="button" class="alert alert-<%= key %> close in pull-left"  data-dismiss="alert" aria-label="close"><%= value%><span aria-hidden="true">&times;</span></div>
	<%end%>
	<%= yield %>

</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development?%>	
</body>

</html>

app/views/microposts/_micropost.html.erb
<li class="list-group-item row">
	<h4><%=micropost.content %></h4>
	<small class='pull-right'>
	Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	</small>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error" >
			The form contains<%= pluralize(object.errors.count,'error')%>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg|%>
			<li>*<%= msg%></li>
			<%end%>
		</ul>
	</div>
<%end%>

app/views/shared/_feed.html.erb
<div class="col-md-12">
	<% if @feed_items.any?%>

	<ul class="list-group">

		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ul>
	<%= will_paginate @feed_items%>
	<%end%>
</div>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item. id %>" class='list-group-item row'>
<%= link_to gravatar_for(feed_item.user), feed_item.user %>
<span>
<%= link_to feed_item.user.name, feed_item.user %>
</span>
<span>
<h4><%=feed_item .content %></h4>
<small class='pull-left'>
<% if current_user?(feed_item.user) %>
<%= link_to "delete", feed_item, method: :delete,
data: { confirm: "You sure?" },
title: feed_item.content %>
<% end %>
</small>
<small class='pull-right'>
Posted <%= time_ago_in_words(feed_item. created_at) %> ago.
</small>
</span>
</li>

app/views/shared/_form.html.erb
<div class="row col-md-9">
	<div class="form-group form-horizontal">
	<%= form_for(@user) do |f|%>
			<%= render 'shared/error_messages' object: f.object%>
			<%= f.label :name%>
			<%= f.text_field :name, class: "form-control"%>
			<%=f.label :email %>
			<%= f.text_field :email, class: "form-control"%>
			<%= f.label :password%>
			<%= f.password_field :password, class: "form-control"%>
			<%= f. label :password_confirmation, "Confirmation"%>
			<%= f.password_field :password_confirmation, class: "form-control"%>
			<br>
			<% if sign_in? %>
			<%= f. submit "Save changes" , class: "btn btn-large btn-primary" %>
			<% else%>
			<%= f. submit "Create my account", class: "btn btn-large btn-primary" %>
			<%end%>
	<%end%>
	</div>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do  |f| %>
 <%= render 'shared/error_messages', object: f.object %>
<div class="field">
<%= f.text_area :content, placeholder: "Compose new micropost...", class: 'form-control'%>
</div>
<%= f. submit "Post", class: "btn btn-large btn-primary" %>
<%  end %> 

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user)%>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h1>
<%= current_user. name %>
</h1>
<span>
<%= link_to "view my profile", current_user %>
</span>
<span>
<%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/static_pages/about.html.erb
<%  provide(:title, 'About Us')  %>

<h1>About Us</h1>
<p>
The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
To get help on this sample app, see the
<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if sign_in? %>
<div class=" row col-md-12">
<div class="col-md-4">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %> 
		</section>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
</div>
<div class="col-md-8">
	<h3>Micropost Feed</h3>
	<%= render 'shared/feed' %>
</div>
</div>
<%else%>
<div class="center hero-unit">
	<h1>Welcome to the Sample App</h1>
	<h2>
		This is the home page for the
		<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</h2>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%end%>

app/views/users/_user.html.erb
	<li >
		<%= gravatar_for user%>
		<%= link_to user.name,user %>
		<% if current_user.admin? && !current_user?(user)%>
			|<%= link_to 'Delete',user,method: :delete,data: {confirm: "You sure?"}%>
		<%end%>
	</li>

app/views/users/edit.html.erb
<% provide(:title,'Edit User')%>
<h1 class="center">Edit User</h1>
<%= render 'shared/form' %>
<%= gravatar_for @user %>
<a href="http://gravatar.com/emails">change</a>

app/views/users/index.html.erb
<%provide(:title,'All users')%>
<%= will_paginate%>
<ul class="users ">
	<%=render @users %>
</ul>
<%= will_paginate%>

app/views/users/new.html.erb
<% provide(:title,'Sign UP')%>
<h1 class="center">Sign Up</h1>
<div>  </div>

			<%= render 'shared/form' %>
			

app/views/users/show.html.erb
<% provide(:title,@user.name)%>
<div class="col-md-4">
	<aside class='span'>
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name%>
			</h1>
		</section>
	</aside>
</div>
<div class="col-md-8">
	<% if @user.microposts.any?%>
	<h3>Microposts:<%= @user.microposts.count %></h3>
	<ul class="list-group">

		<%= render @microposts %>
	</ul>
	<%= will_paginate @microposts%>
	<%end%>
</div>